
import Navbar from "./components/Navbar";
import "./globals.css";



export const metadata = {
  title: "Productos de calidad",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="icon"href="/favicon.io"/>
      <body
        className={''}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
